### ISSUE TITLE
Error sending image

### ISSUE THREAD

**Issue by matiastucci** [hidespb/node-whatsapi#46] opened 2015-05-03 00:30 UTC
When I try to send an image I'm getting this error: `Segmentation fault: 11`

My code looks like this:

  `wa.sendImage(targets[i], 'http://lorempixel.com/100/100/?.jpg', function(err) {
      if (err) { printError(err.message); return; }
  });`

I'm doing something wrong?
Thanks!

**Comment by matteocontrini** [comment] 2015-05-03 16:53
Can you post the debug log? Where do you get that error?

**Comment by matiastucci** [comment] 2015-05-03 18:56
That error appears in my console when I don't declare any `imageTool` property (JIMP default). I just installed IMAGEMAGICK and when y set that tool in the adapter, it works. I don't know why with JIMP doesn't.

**Comment by matteocontrini** [comment] 2015-05-03 19:18
If you believe the problem is with Jimp (and you can reproduce it), a good idea would be to [extract](https://github.com/hidespb/node-whatsapi/blob/master/extensions/media.js#L298) a piece of code and report it on the official [Jimp](https://github.com/oliver-moran/jimp) repository.

Considered that you solved the issue using the alternative ImageMagick tool (although GraphicsMagick is suggested), I'll close the issue here.

**Closed by matteocontrini** 2015-05-03 19:18 UTC
