### ISSUE TITLE
Image messages with non latin caption don't sent

### ISSUE THREAD

**Issue by WilixLead** [hidespb/node-whatsapi#58] opened 2015-05-28 12:01 UTC
Hello,

I get strange issue. When I try send message with text and caption with using function sendImage message not sent if caption not in English (In my case it Russian).
I enable debug and see something like this:

tx <message to="xxxxxxxx@s.whatsapp.net" type="media" id="message-1432813932-4" t="1432813932">
tx   <media xmlns="urn:xmpp:whatsapp:mms" caption="Русский текст" url="https://mmi222.whatsapp.net/d/AtwOfKm_q8Dmn5tnlQw1LSK6tavBe6r6-W4yRonEo5UE.jpg" type="image" size="361100" file="AtwOf....

but message don't send and callback not called.
If I try send image with English caption, all works fine.
Help me please. I don't understand what happen

**Comment by matteocontrini** [comment] 2015-05-28 12:29
Probably related to #41

**Comment by amozgachev** [comment] 2015-05-29 15:40
This is an old problem.
Not only images are affected - also audio, map, vcard...
It's not #41

**Comment by matteocontrini** [comment] 2015-05-29 15:59
It could be because it happens when non-ASCII characters are involved

**Comment by webjoel** [comment] 2015-06-11 17:30
Caption with accents also does not send the image, example: "áéó".

**Comment by brunocascio** [comment] 2015-06-11 19:41
This library maybe resolve this problem: [mimelib](https://github.com/andris9/mimelib)

**Comment by WilixLead** [comment] 2015-06-13 11:07
@brunocascio can you please explain what function from Mimelib you propose to use? encodeMimeWord? Or can you show example? 
Thanks

**Comment by brunocascio** [comment] 2015-06-13 17:25
I use these lib in my [android-vcf](https://github.com/brunocascio/android-vcf) library.

When read vcf files, words with accents like `Lu León` in .vcf output is `=4C=75=20=4C=65=C3=B3=6E`, so the lib convert `=4C=75=20=4C=65=C3=B3=6E` in `Lu León`.

for this, `mimelib.decodeQuotedPrintable("=4C=75=20=4C=65=C3=B3=6E");` make it work.

**Comment by matteocontrini** [comment] 2015-06-13 19:17
How is this related? I don't get it. Even if we encode the characters in some way, I don't think other WhatsApp clients are able to handle them.

**Comment by WilixLead** [comment] 2015-06-13 20:55
I found another bug, and I think it related with this bug. If I set username in Cyrillic I can't send messages, make contact's sync and some other operations. One I change username to English all works.
Looks like need additional encoding in protocol level or another place. 
Whats the encoding used for simple messages? Why they normally sends with any characters?

**Comment by matteocontrini** [comment] 2015-06-14 16:20
In fact there's a similar issue with simple messages as well. See #41

UTF-8 messages were made possible with #14 and PR #16. Maybe the problem is there?

**Comment by AminaG** [comment] 2015-08-20 04:06
+1

**Comment by AminaG** [comment] 2015-08-20 08:43
The commit solve my issue. I reccomend to other users with same problem, to update the protocol.js file from this commit. The NPM package is not updated as the master branch here.

**Comment by matteocontrini** [comment] 2015-08-20 08:47
You mean the latest commit (9b879639440d5c47f9ced314735fd46ab2720484) which deals with de-compression?

**Comment by AminaG** [comment] 2015-08-20 19:06
I mean this commit:
https://github.com/brunocascio/node-whatsapi/commit/ca826186f51e59b767478a61fc9130cbd7d6f8cd

**Comment by matteocontrini** [comment] 2015-08-20 19:07
Can someone other confirm?

**Comment by tvandergeer** [comment] 2015-08-20 20:43
Yes, I can confirm that this single line fixes the issue that @WilixLead addressed in this issue.

**Closed by tvandergeer** 2015-08-20 20:43 UTC
Labels: bug

**Comment by matteocontrini** [comment] 2015-08-20 20:45
Well, so thank you very much @WilixLead :)

**Comment by matteocontrini** [comment] 2015-08-24 16:23
[Released](https://github.com/hidespb/node-whatsapi/releases/tag/v1.3.4).

And thatnks to @brunocascio, he's the author of that commit ;)

**Comment by brunocascio** [comment] 2015-08-24 16:59
You're welcome @matteocontrini  :)

I will continue contributing (Y)

**Comment by WilixLead** [comment] 2015-08-25 08:17
Wow! Cool. Thanks for all!
